name: Build DeSmuME AppImage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build DeSmuME AppImage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install libfuse2 and Qt dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libfuse2 qtbase5-dev qtchooser

      - name: Install dependencies
        run: sudo apt update && sudo apt install meson libsdl2-dev libpcap-dev libgtk-3-dev libgtk2.0-dev autoconf libglu1-mesa-dev

      - name: Build DeSmuME
        run: |
          cd desmume/src/frontend/posix/
          meson build
          ninja -C build

      - name: Create AppDir directory
        run: mkdir -p AppDir

      - name: Copy Desktop File to AppDir
        run: cp desmume/src/frontend/posix/gtk2/desmume.desktop AppDir/
             cp desmume/src/frontend/cocoa/images/Icon_DeSmuME_32x32.png AppDir/DeSmuME.png
             cp desmume/src/frontend/posix/gtk/org.desmume.DeSmuME.svg AppDir/
             cp desmume/src/frontend/posix/gtk2/DeSmuME.xpm AppDir/

      - name: Set Qt environment variable
        run: export QTDIR=/usr/lib/qt5

      - name: Install linuxdeploy and plugins
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod a+x linuxdeploy-x86_64.AppImage
          chmod a+x linuxdeploy-plugin-qt-x86_64.AppImage

      - name: Build AppImage
        run: |
          export ARCH=x86_64  # Definir la variable de entorno ARCH
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage
          mkdir dist
          mv ./AppDir/*.AppImage dist/

      - name: Find AppImage File
        run: |
          # Buscar el archivo AppImage generado en la carpeta dist
          appimage_path=$(find dist -name "*.AppImage" -type f)
          
          # Verificar si se encontr√≥ el archivo AppImage
          if [[ -n "$appimage_path" ]]; then
            echo "Archivo AppImage encontrado en la ruta: $appimage_path"
            # Puedes usar la variable $appimage_path para referencia futura
          else
            echo "Archivo AppImage no encontrado."
            exit 1
          fi

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v2
        with:
          name: desmume-appimage
          path: ./dist/
